### ISSUE TITLE
修改模型，删除某个或某几个字段（删除字段在全文检索配置中已用），重新构建不成功

### ISSUE THREAD

**Issue by yuanhj3** [AIPaaS/SES#17]
测试步骤：
1.修改已经成功构建的模型，删除某个或某几个字段（删除字段在全文检索配置中已用）
2.点击开始构建按钮，按钮一直处于“正在创建……”状态

建议：构建时检查全方检索配置字段是否存在，若不存在应给出操作提示

**Comment by smilence1986** [comment]
删除某个或某几个字段会同时删除全文检索配置中的字段
